[project]
name = "new-vpn-registration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.30.0",
    "aiohttp-socks>=0.12.0",
    "aiosqlite>=0.22.1",
    "dotenv>=0.9.9",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "qrcode>=8.2",
    "requests>=2.34.2",
    "ruff>=0.16.8",
    "sqlalchemy>=2.0.52",
    "uv>=0.12.5",
]
